spring.datasource.url=jdbc:postgresql://localhost:5432/HotelBooking
spring.datasource.username=postgres
spring.datasource.password=190902
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.output.ansi.enabled=always
#Hot reload for Thymeleaf
spring.thymeleaf.cache=false

#Need an existing table for init
#spring.sql.init.mode=always